/* 像素化演算法載入清單：CLI、benchmark、check 共用，避免三份各寫各的。
   路徑相對 repo 根目錄。Worker 的 importScripts 用同一組檔名、前綴不同。 */
module.exports = [
  'js/pixelate/lib/colour.js',
  'js/pixelate/lib/profile.js',
  'js/pixelate/lib/fft.js',
  'js/pixelate/lib/morph.js',
  'js/pixelate/lib/canny.js',
  'js/pixelate/grid.js',
  'js/pixelate/detect/legacy.js',
  'js/pixelate/detect/autocorr.js',
  'js/pixelate/detect/runlength.js',
  'js/pixelate/detect/selfsim.js',
  'js/pixelate/detect/fft.js',
  'js/pixelate/detect/perfecter.js',
  'js/pixelate/detect/hough.js',
  'js/pixelate/detect/runs.js',
  'js/pixelate/detect/arbitrate.js',
  'js/pixelate/sample/center-median.js',
  'js/pixelate/sample/two-stage.js',
  'js/pixelate/sample/stats.js',
  'js/pixelate/sample/geomedian.js',
  'js/pixelate/sample/pixeloe.js',
  'js/pixelate/quant/oklab-kmeans.js',
  'js/pixelate/quant/median-cut.js',
  'js/pixelate/dither/adapter.js',
  'js/pixelate/clean/bg.js',
  'js/pixelate/clean/morph.js',
  'js/pixelate/index.js',
];
